### ISSUE TITLE
Invalid domain name with #?# and #id selector

### ISSUE THREAD

**Issue by scripthunter7** [abpvn/abp-rule-checker#1]
@hoang-rio Hello!

If I use the #?# syntax with a selector that starts with an element ID, the [tool](https://abpvn.com/ruleChecker/redundantRuleChecker.html) will show the domain name as invalid:

```
example.com#?##some-id:-abp-has(.some-child)
```

> **The following error, warning or optimalization was encountered while checking the rules:**
> example.com#?##some-id:-abp-has(.some-child) : Domain 'example.com#?' isn't a valid domain

However, it works with classes: 
```
example.com#?#.some-class:-abp-has(.some-child)
```

If you are still interested in this project and if you have some free time, could you please fix this problem? :)

Thank you!

**Comment by hoang-rio** [comment]
I'm not sure about my free time but I will try to fix it when posible

**Comment by hoang-rio** [comment]
@scripthunter7 This issue is now fixed. Please enjoy it [here](https://abpvn.com/ruleChecker/redundantRuleChecker.html)
